pipeline {
    agent any
    environment {
        RELEASE = '0.0.1'
    }

    stages {
        stage('Build') {
            agent any
            environment {
            LOG_LEVEL = 'INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            // input: wait some info from the user
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to env ${TARGET_ENVIRONMENT}"
            }
        }
    }
}